# Generated by Django 4.2.27 on 2026-03-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchactivity',
            name='book_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='researchactivity',
            name='editors',
            field=models.TextField(blank=True, null=True),
        ),
    ]
