# Generated by Django 6.1.1 on 2026-09-10 04:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_researchactivity_book_title_researchactivity_editors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchactivity',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1980)]),
        ),
    ]
