# Generated by Django 6.1.1 on 2026-09-10 14:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_researchactivity_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalIndexStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('scopus', 'Scopus'), ('web_of_science', 'Web of Science'), ('other_recognised_index', 'Other recognised index'), ('not_indexed', 'Not indexed'), ('not_applicable', 'Not applicable')], max_length=40, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Journal Index Statuses',
            },
        ),
        migrations.CreateModel(
            name='InternationalProfessionalFellowship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('year_elected', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='international_professional_fellowships', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name_plural': 'International Professional Fellowships',
                'ordering': ['-year_elected'],
            },
        ),
        migrations.CreateModel(
            name='EditorialAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_name', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('editor_in_chief', 'Editor-in-Chief'), ('managing_editor', 'Managing Editor'), ('associate_deputy_editor', 'Associate/Deputy Editor'), ('section_handling_editor', 'Section/Handling Editor'), ('editorial_board_member', 'Editorial Board Member'), ('guest_editor', 'Guest Editor'), ('series_editor', 'Series Editor'), ('other_editor', 'Other')], max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_appointments', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('indexing_status', models.ManyToManyField(blank=True, related_name='editorial_appointments', to='api.journalindexstatus')),
            ],
            options={
                'verbose_name_plural': 'Editorial Appointments',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NationalAcademyFellowship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academy_name', models.CharField(max_length=255)),
                ('academy_type', models.CharField(choices=[('national_academy_of_science', 'National Academy of Science'), ('national_academy_of_engineering', 'National Academy of Engineering'), ('national_academy_of_medicine', 'National Academy of Medicine'), ('national_academy_of_education', 'National Academy of Education'), ('national_academy_of_letters_arts', 'National Academy of Letters/Arts'), ('other_national_scholarly_academy', 'Other recognised national scholarly academy')], max_length=60)),
                ('year_elected', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
                ('discipline', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='national_academy_fellowships', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name_plural': 'National Academy Fellowships',
                'ordering': ['-year_elected'],
            },
        ),
        migrations.CreateModel(
            name='ResearchAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.CharField(max_length=255)),
                ('awarding_organization', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('year_received', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
                ('award_category', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_awards', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name_plural': 'Research Awards',
                'ordering': ['-year_received'],
            },
        ),
        migrations.CreateModel(
            name='ResearchGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('group_type', models.CharField(choices=[('oou_research_cluster', 'OOU Research Cluster'), ('oou_research_centre', 'OOU Research Centre/Institute'), ('departmental_research_group', 'Departmental Research Group'), ('faculty_research_group', 'Faculty Research Group'), ('national_research_group', 'National Research Group/Network'), ('international_research_group', 'International Research Group/Network'), ('interdisciplinary_research_group', 'Interdisciplinary Research Group'), ('other_research_group', 'Other')], max_length=40)),
                ('research_area', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(choices=[('coordinator', 'Coordinator/Leader'), ('co_coordinator', 'Co-Coordinator'), ('member', 'Member'), ('research_associate', 'Research Associate'), ('other_role', 'Other')], max_length=40)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('newly_established', 'Newly established'), ('under_development', 'Under development')], max_length=20)),
                ('number_of_members', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_group_memberships', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name_plural': 'Research Group Memberships',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='VisitingProfessorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_institution', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('title', models.CharField(choices=[('visiting_professor', 'Visiting Professor'), ('visiting_research_professor', 'Visiting Research Professor'), ('visiting_scholar', 'Visiting Scholar')], max_length=40)),
                ('year_appointed', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visiting_professorships', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name_plural': 'Visiting Professorships',
                'ordering': ['-year_appointed'],
            },
        ),
    ]
