# Generated by Django 6.1.1 on 2026-09-10 14:10

from django.db import migrations


def create_index_statuses(apps, schema_editor):
    JournalIndexStatus = apps.get_model('api', 'JournalIndexStatus')
    JournalIndexStatus.objects.get_or_create(name='scopus')
    JournalIndexStatus.objects.get_or_create(name='web_of_science')
    JournalIndexStatus.objects.get_or_create(name='other_recognised_index')
    JournalIndexStatus.objects.get_or_create(name='not_indexed')
    JournalIndexStatus.objects.get_or_create(name='not_applicable')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_journalindexstatus_and_more'),
    ]

    operations = [
        migrations.RunPython(create_index_statuses, reverse_code=migrations.RunPython.noop),
    ]
