# Generated by Django 6.1.1 on 2026-09-12 06:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_journal_index_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorialappointment',
            name='indexing_status',
        ),
        migrations.AddField(
            model_name='editorialappointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='editorialappointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='internationalprofessionalfellowship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationalprofessionalfellowship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nationalacademyfellowship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nationalacademyfellowship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='researchaward',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchaward',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='researchgroupmembership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchgroupmembership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='visitingprofessorship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitingprofessorship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='editorialappointment',
            name='position',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='nationalacademyfellowship',
            name='academy_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='researchgroupmembership',
            name='group_type',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='researchgroupmembership',
            name='role',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='researchgroupmembership',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='visitingprofessorship',
            name='title',
            field=models.CharField(max_length=40),
        ),
        migrations.DeleteModel(
            name='JournalIndexStatus',
        ),
        migrations.AddField(
            model_name='editorialappointment',
            name='indexing_status',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
