# Generated by Django 6.1.1 on 2026-09-12 22:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_editorialappointment_indexing_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchactivity',
            name='authorship',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='researchactivity',
            name='journal_index',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='researchactivity',
            name='sdg_alignment',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.CreateModel(
            name='ActiveResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('source_of_funding', models.CharField(blank=True, max_length=300)),
                ('year_commenced', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1980)])),
                ('expected_year_of_completion', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1980)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_research_projects', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name_plural': 'Active Research Projects',
                'ordering': ['-year_commenced'],
            },
        ),
        migrations.CreateModel(
            name='CompletedResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('year_commenced', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1980)])),
                ('year_completed', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1980)])),
                ('output_status', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_research_projects', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name_plural': 'Completed Research Projects',
                'ordering': ['-year_completed'],
            },
        ),
        migrations.CreateModel(
            name='PhDThesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('candidate_name', models.CharField(max_length=255)),
                ('year_awarded', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1980)])),
                ('research_area', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phd_theses', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name_plural': 'PhD Theses',
                'ordering': ['-year_awarded'],
            },
        ),
    ]
