# Generated by Django 6.1.1 on 2026-09-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_researchactivity_authorship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchactivity',
            name='no_of_citations',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
